// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBmDaeeOIIspLCTlS60rmSq122E2ut8gMI',
    appId: '1:737427767164:web:81ca177b4a5a94345b6ef9',
    messagingSenderId: '737427767164',
    projectId: 'retaurant-app-ce20e',
    authDomain: 'retaurant-app-ce20e.firebaseapp.com',
    storageBucket: 'retaurant-app-ce20e.appspot.com',
    measurementId: 'G-S0YL47HX4K',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDYIHMbAXyIPmdYc3QhSrdaeYfSHpyWmlA',
    appId: '1:737427767164:android:b6aa25b026d6ff215b6ef9',
    messagingSenderId: '737427767164',
    projectId: 'retaurant-app-ce20e',
    storageBucket: 'retaurant-app-ce20e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBJbMx6TPWka930lyTjP0oomkYBO37KzSM',
    appId: '1:737427767164:ios:f25a03853f29acd65b6ef9',
    messagingSenderId: '737427767164',
    projectId: 'retaurant-app-ce20e',
    storageBucket: 'retaurant-app-ce20e.appspot.com',
    iosClientId: '737427767164-h19j3crqbsv4s0u04lajgeb25rfnoeds.apps.googleusercontent.com',
    iosBundleId: 'com.example.monkeyAppDemo',
  );
}
